//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySinhVien5ToT
{
    using System;
    using System.Collections.Generic;
    
    public partial class CURRENT_QUYDINH_DIEM
    {
        public int MaQuyDinhDiem { get; set; }
        public Nullable<int> MaLoaiDiem { get; set; }
        public Nullable<int> DiemToiThieu { get; set; }
        public string MaDonVi { get; set; }
        public Nullable<int> MaTieuChuan { get; set; }
        public Nullable<int> Mathoigian { get; set; }
    }
}
